### ISSUE TITLE
Scrollbar causing layout error

### ISSUE THREAD

**Issue by aleksmont** [creativetimofficial/ct-now-ui-dashboard-pro-react#1]
[https://ibb.co/hAskqn](url)

There is an error in the side menu when a scrollbar appears.

**Comment by einazare** [comment]
Hello @aleksmont ,

Thank you for your interest in our product.
The link you have given goes to a 404 page.
Could you please change the link with the correct one, or could you give us more details on what the issue is?

Thank you,
Manu

**Comment by hervesoulie** [comment]
This issue is related to PerfectScrollbar which is not active in the sidebar on Chrome (at least the latest mac version)
https://i.imgur.com/scV9hbp.png

Sorry but there's no message in the JS console.
Please note that this issue is also visible your other products which use this lib.
<img width="396" alt="capture d ecran 2018-02-27 a 23 47 26" src="https://user-images.githubusercontent.com/18396220/36770652-802174ac-1c19-11e8-9fdb-73669e7b0634.png">

[edit] this issue is reproductible with safari mac (11.0.3) and firefox mac (49.01), too

**Comment by einazare** [comment]
Hello @hervesoulie 

Thank you for your interest in our product.
I've just done some testings on safari mac 11.0.3 and it seems that everything is fine on my machine.
There are some things that i do not understand from your comment. You say that perfect-scrollbar isn't active, yet you say that the issue appears from it. So i have the following questions:

1. How do you know this issue is from perfect-scrollbar?
2. Is perfect-scrollbar active?
3. Have you done the testing without perfect-scrollbar? (this means that you have deleted perfect-scrollbar from node_modules and deleted the scss from assets)
4. Have you changed any of our scss lines?
5. Have you added new scss/css?

Best,
Manu

**Comment by hervesoulie** [comment]
Hello @EINazare 

> How do you know this issue is from perfect-scrollbar?

I had the same issue with material dashboard. 

>Is perfect-scrollbar active?

Well, as far as I can see (check the screenshots I posted earlier), it doesn't look like

>Have you done the testing without perfect-scrollbar? (this means that you have deleted perfect-scrollbar from node_modules and deleted the scss from assets).

No. I haven't dowloaded the project. I just went on the preview https://timcreative.github.io/now-ui-dashboard-pro-react/

**Comment by dbozarth** [comment]
I have the same issue. It only happens during the minified menu where the buttons do not center to the icons or the text making the minified sidebar appear broken. It functions well but renders incorrectly.

**Comment by dbozarth** [comment]
It seems it has to do with the width property when the scrollbar appears. The scrolbar itself is using the available space pushing the other elements left to ensure the scrollbar is rendered fully.

**Comment by senorcodecat** [comment]
Also have this same issue.

**Comment by einazare** [comment]
Hello @senorcodecat ,

Can you tell me on what machine are you experiencing this issue? 
I want to know operating system + browser + browser version.
And also would like to see a video with this issue happening. 
I was not able to recreate the issue, and maybe seeing a video may help me recreate it and manage to come up with a solution.

Best,
Manu

**Comment by senorcodecat** [comment]
This is probably actually unrelated, but I'll leave here just in case: 

![image](https://user-images.githubusercontent.com/26010572/39435254-e0e2b5ba-4c68-11e8-92a5-e4ed18ca5a73.png)

We are getting these scroll bars everywhere in Chrome on Windows.

**Comment by einazare** [comment]
Hello @senorcodecat ,

Thank you for that image.
You can solve this issue by modifying in our scss the .table-responsive from:
```
table-responsive {
        overflow: scroll;
}
```
to
```
table-responsive {
        overflow: auto;
}
```
Or you could initiate the perfect-scrollbar plugin on each of them to get nice scrollbars.
As for the sidebar, i do not know what the problem is there, on our machines the sidebar is lookin great.
![31743550_10209198036066404_5503854762799398912_n](https://user-images.githubusercontent.com/26245512/39507476-b2155178-4de6-11e8-8c5d-242bd74b2727.png) 

Best,
Manu
