### ISSUE TITLE
1 Chart bug and scroll problems

### ISSUE THREAD

**Issue by chichi13** [creativetimofficial/ct-now-ui-dashboard-pro-react#2]
Hello and congratulation for your work !

I've bought this template yesterday and I discovered 3 problems : 
- https://image.noelshack.com/fichiers/2018/10/2/1520346606-bugchart.png As you can see we don't see settings in "/charts" :(
- I can't scroll the website with the mouse-click wheel
- The last problem is that the scroll system is not fluid

Could you fix this please ? If you need more informations, feel free to ask :D 
However this template is awesome, thank you !

Edit : React version

**Comment by einazare** [comment]
Hello @chichi13 ,

Thank you for using our product.
For the first problem (the chart dropdown):
 - go in `src/assets/scss/now-ui-dashboard/_cards.scss` and delete lines 10, 11 and 12, you'll have to delete this:
```
    &.card-chart{
      overflow-x: hidden;
    }
```
 - after this you will have to add `right` property on the dropdowns, for this you'll have to go in `src/views/Dashboard/Dashboard.jsx` and change lines 119 and 155 from 
```
<DropdownMenu>
```
to 
```
<DropdownMenu right>
```

For the second problem i would like to know what operating system are you running on. Also if you could detail what do you mean by `fluid`. Do you mean that it lags? 

Best, 
Manu

**Comment by chichi13** [comment]
Thank you for the first solution, I'll try this as soon as possible.

For the second problem, here is a video : https://youtu.be/Tggs9LqXlYw You can see, google is smooth unlike the other website. It happens on every browsers I use (Brave, Chrome, Firefox). I didn't try on safari yet.

Do you know what I mean for the "scroll the website with the mouse-click wheel" ?

Best regards.

**Comment by dbozarth** [comment]
Scrolling is an issue. Typically on a web page view when one scrolls either by a mouse wheel or on mobile by touch up/down gesture the page will scroll continuous until the wheel stops or on mobile the time out for scroll animation on gesture is finished. 

On the templates this does not work and simply moves as if it were clogging. 

I assume this is a rendering issue. Each time you scroll the page lags during the render causing a major delay short circuiting the scroll method. 

Not sure if it is from React or a plug-in.

Regardless of the OS the issue is present leading me to think the issue is central to the template package.

**Comment by dbozarth** [comment]
It seems that it happens when the first issue widget is present. So, possibly adding an overflow-y: scroll and the same for webkit could solve the issue for mobile by adding the touch similar to this.

`overflow-y: scroll;
  -webkit-overflow-scrolling: touch;`

There is an npm library hat addresses the issue but I think simply adding this to the css would be sufficient.

**Comment by chichi13** [comment]
Ok I understand.
But in which **css** file should I add this line ? Which line ?

Thank you in advance.

**Comment by dbozarth** [comment]
I am still researching. And I am a customer not the official developer.

Kind Regards,

Don Bozarth
President
FuelCNC Engineering Services
m: 832-339-3322
w: FuelCNC.com e: don@fuelcnc.com

**Comment by chichi13** [comment]
Oh okay sorry ! Thank you @dbozarth

**Comment by dbozarth** [comment]
No worries. There is a solution. Just not self evident yet...

Kind Regards,

Don Bozarth
President
FuelCNC Engineering Services
m: 832-339-3322
w: FuelCNC.com e: don@fuelcnc.com

**Comment by einazare** [comment]
@chichi13 you should add those lines of css in `src/assets/scss/now-ui-dashboard/_sidebar-and-main-panel.scss` at line 504, instead of
```
.perfect-scrollbar-off{
    .sidebar .sidebar-wrapper,
    .main-panel{
        overflow: auto;
    }
}
```
you should put 
```
.perfect-scrollbar-off{
    .sidebar .sidebar-wrapper,
    .main-panel{
        overflow-y: scroll; 
        -webkit-overflow-scrolling: touch;
    }
}
```
or you should put
```
.perfect-scrollbar-off{
    .sidebar .sidebar-wrapper,
    .main-panel{
        overflow: auto;
        -webkit-overflow-scrolling: touch;
    }
}
```

On my machine everything works fine and i can't be sure which one is the correct one.

Best,
Manu

**Comment by chichi13** [comment]
Thank you, it's working well on mobile now !

But unfortunately not very fluid on the computer. It's jerky. Not only for me, for my collagues too.

**Comment by einazare** [comment]
@chichi13 can you please tell me on what operating system are you using, and what browser?

Thank you,
Manu

**Comment by chichi13** [comment]
I'm using Firefox/Chrome on Windows. But it's working well on Mac OS.

**Comment by einazare** [comment]
Ok, i'll do some testings on Windows, see what i can find. I think the jerky scroll is caused by the perfect-scrollbar plugin.

**Comment by einazare** [comment]
Hello @chichi13 ,

Sorry for coming back so late.
We've done some testing on Windows, and on our machines everything works correctly (i am speaking about the scroll).
For our testing we've used Firefox 59.0.1, Chrome 65.0.3325.181 and Microsoft Edge 40.15063.674.0 .
Can you tell us what versions have you been using for your testings and if the problem is still there?

Best,
Manu
