### ISSUE TITLE
[Feature Request] sidebar does't update when I click subItems

### ISSUE THREAD

**Issue by chris0906** [creativetimofficial/ct-now-ui-dashboard-pro-react#25]
### What is your enhancement?
the original Now Ui seems ok, but when I move it into my react app, the sidebar doesn't highlight the subitems when I click it. But after I click the collapse Items, it will update the previous state which will highlight the sub item I clicked before.

**Comment by chris0906** [comment]
simply put this.setState({state:this.state}), but I still don't know why the original Now Ui could re render without any state being changed

**Comment by einazare** [comment]
Hello there, @chris0906 ,

Thank you for your interest in working with our products.
Is this still an issue/enhancement?

Best,
Manu

**Comment by chris0906** [comment]
for the login page, when I input the email by my own, the background
remains good, whereas when I choose the default email from the dropdown
list, the background color will be covered.

Nazare Emanuel-Ioan <notifications@github.com> 于2019年7月8日周一 下午2:49写道：

**Comment by einazare** [comment]
Hello again, @chris0906 ,

Unfortunately, that is default behavior from your browser.
That cannot be changed.
If you change the browser that you are using, you will see different behaviors.
I am truly sorry, but we've faced with the same issue, and cannot change it - to change that would require to make our own browser or something :)).

Best,
Manu

**Comment by chris0906** [comment]
Hi, glad that you tell me that, So there is another tiny issue when I
switch to login page there is a red color flashing through. how do you
think to solve it? thank you very much.

Nazare Emanuel-Ioan <notifications@github.com> 于2019年7月9日周二 下午5:44写道：

**Comment by einazare** [comment]
Hello again, @chris0906 ,

I am not sure, but I believe it is because of the background image not being initialized.
You can take another image, something very small in dimension on the disk, something like 500-700KB.
If this is not the case, could you please make a video with the issue?
On my machine, it seems to work fine.

Best,
Manu

**Comment by chris0906** [comment]
thanks!
when I am using the react-select component, I was trying to change the
outline color, but I failed to change it, its default color is red when
it's focused, how can I change to green. the example code is below:

import Select from "react-select";
<Select
className="react-select primary"
classNamePrefix="react-select"
placeholder="Single Select"
name="singleSelect"
value={this.state.singleSelect}
options={selectOptions}
onChange={value =>
this.setState({ singleSelect: value })
}
/>


Nazare Emanuel-Ioan <notifications@github.com> 于2019年7月11日周四 下午10:25写道：

**Comment by einazare** [comment]
Hello there, @chris0906 ,

Go inside `src/assets/scss/now-ui-dashboard/react/plugins/_plugin-react-select.scss`
At line 140 you will find that color.

Best,
Manu

**Comment by chris0906** [comment]
thanks, Manu, really appreciate your help. and right now I met other issues:
1)
[image: image.png]
for this wizard page, when my cursor hovers over to what's been
highlighted, the cursor shows as a pointer, but when I move my cursor to
the other title such as configure sequence and test, the cursor shows like
an input cursor style.

2)
[image: image.png]
for the sidebar background color, we have defined several internal colors
which showed above, how can I add my own color to it, for example, I want
to define a color called XYZ and add it to this background-color.

best
Chris


Nazare Emanuel-Ioan <notifications@github.com> 于2019年7月16日周二 下午7:29写道：

**Comment by einazare** [comment]
Hello again, Chris,

The images were not sent. This is because you have responded from your email (the images have only remained on your email, probably - or maybe they are lost forever).
Please open Github and come here to add the images.
![Screen Shot 2019-07-18 at 8 00 01 AM](https://user-images.githubusercontent.com/26245512/61430279-2e320600-a932-11e9-9660-94cd4505e5fd.png)
So for the first question, I cannot give you a response. I do not understand your details.
For the second question, you need to add the following css to your styles:
```
.sidebar[data-color="your-color-name"]:after,
.off-canvas-sidebar[data-color="your-color-name"]:after {
  background-color: XYZ;
}
```

Hope this helps.

Best,
Manu

**Comment by chris0906** [comment]
thank you for telling me that, I have already uploaded to GitHub issue
Chanel

Nazare Emanuel-Ioan <notifications@github.com> 于2019年7月18日周四 下午3:06写道：
