### ISSUE TITLE
[Bug] React-Select Dropdown default value is not working.

### ISSUE THREAD

**Issue by kaleem-izylogic** [creativetimofficial/ct-now-ui-dashboard-pro-react#28]
### Version
1.3.0
### Reproduction link
https://localhost:44340/admin/additem
### Operating System
any
### Device
any
### Browser & Version
any
### Steps to reproduce
Trying to select default value from database but its not working
### What is expected?
it should select the selected value in dropdown list (select)
### What is actually happening?
nothing is selected 

---

**Comment by einazare** [comment]
Hello there, @kaleem-izylogic ,

Thank you for your interest in working with our products.
I believe you just need some help, and this is not actually a bug, since you can easily add a default selected value for the React-Select.
Please read the official readme docs of React-Select to learn how to do so: https://github.com/JedWatson/react-select
Also, you can check their live docs here: https://react-select.com/home
These links can be also found inside our live docs of React-Select: https://demos.creative-tim.com/now-ui-dashboard-pro-react/#/documentation/customizable-select
I do not know if you know this, but the link provided is localhost, this means only you have access to it.

Best,
Manu

**Comment by kaleem-izylogic** [comment]
Dear,
I had followed the links... The problem is that its not working despite following the exact example.
For example I want to bind by value e.g 18, not by display value. As you have modified the react-select and it does not render as it '<select>' element. Please make a simple example for me, How can I bind element by value in select in this template on page load. Thanks in anticipation.

**Comment by einazare** [comment]
Hello again, @kaleem-izylogic ,

> As you have modified the react-select and it does not render as it '' element.

We've only modified the css/scss of it. The rendering should not be affected by our styles.
Please give me an exact example of the react-select working with what you are trying to achieve.
As I've understood from your comment, if I create a new React project, say using creat-react-app, and I install && import the react-select library, your use case will work, right?
Please give me all the necessary steps to make it work on a new project and I will see why or what is it not working in our product.
If I go inside our product and set a default value, using the official react-select docs, everything works just fine.

Best,
Manu
