### ISSUE TITLE
[Bug] Unable to run npm install

### ISSUE THREAD

**Issue by dhavalmshah** [creativetimofficial/ct-now-ui-dashboard-pro-react#37]
### Version
1.5.0
### Reproduction link
https://jsfiddle.net/
### Operating System
Windows 10
### Device
PC
### Browser & Version
NA
### Steps to reproduce
1. Run the command `npm install`
### What is expected?
All dependencies get downloaded.
### What is actually happening?
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: now-ui-dashboard-pro-react@1.5.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

---

**Comment by dhavalmshah** [comment]
Is possible please include package-lock.json in the zip file so that we do not face the dependencies issues

**Comment by atonb117** [comment]
Had the same problem.

You have to manually change to react-datetime @3.1.1 but the install will next hang on react-tags-input.  That's the problem I am having now.

**Comment by hendradra1234** [comment]
i have more worst problem than this, i cannot install other library, and i cannot run the template, my compiler show this error 
Failed to load config "react-app" to extend from.
Referenced from: C:\Users\ASUS\Documents\SCHOOL COURSE and COLLEGE\Artamedia\Main Project Consumer API bridge\javascript\FrontEnd\package.json
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tm

**Comment by shanvaz123** [comment]
Hi,

I also facing the same issue.

I have following installed in my windows system
Nodejs v 16.3.2
node-gyp v 8.4.1
also I have python 2.7 and 3.1 installed

But when I run npm install i am getting below errors, whats wrong with it? or u need to update your gulpfile dependeices versions to latest?

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Users\user\AppData\Roaming\npm\node_modules\node\bin\node.exe C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! Build started 2022-02-03 10:37:27 AM.
npm ERR! Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
npm ERR! ValidateSolutionConfiguration:
npm ERR! Building solution configuration "Release|x64".
npm ERR! Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.sln" (1) is building "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
npm ERR! Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
npm ERR! C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install
the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\src\libsass.vcxproj]
npm ERR! Done Building Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
npm ERR! Done Building Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
npm ERR! Done Building Project "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.
npm ERR!
npm ERR! Build FAILED.
npm ERR!
npm ERR! "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.sln" (default target) (1) ->
npm ERR! "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
npm ERR! "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
npm ERR! (Desktop_PlatformPrepareForBuild target) ->
npm ERR! C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\src\libsass.vcxproj]
npm ERR!
npm ERR! 0 Warning(s)
npm ERR! 1 Error(s)
npm ERR!
npm ERR! Time Elapsed 00:00:00.10
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli 'C:\Users\user\AppData\Roaming\npm\node_modules\node\bin\node.exe',
npm ERR! gyp verb cli 'C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\bin\node-gyp.js',
npm ERR! gyp verb cli 'rebuild',
npm ERR! gyp verb cli '--verbose',
npm ERR! gyp verb cli '--libsass_ext=',
npm ERR! gyp verb cli '--libsass_cflags=',
npm ERR! gyp verb cli '--libsass_ldflags=',
npm ERR! gyp verb cli '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb which failed Error: not found: python2.7
npm ERR! gyp verb which failed at getNotFoundError (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:13:12)
npm ERR! gyp verb which failed at F (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:68:19)
npm ERR! gyp verb which failed at E (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:80:29)
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:89:16
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\isexe\index.js:42:5
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb which failed at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb which failed python2.7 Error: not found: python2.7
npm ERR! gyp verb which failed at getNotFoundError (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:13:12)
npm ERR! gyp verb which failed at F (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:68:19)
npm ERR! gyp verb which failed at E (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:80:29)
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\which\which.js:89:16
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\isexe\index.js:42:5
npm ERR! gyp verb which failed at C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb which failed at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb which failed code: 'ENOENT'
npm ERR! gyp verb which failed }
npm ERR! gyp verb could not find "python2.7". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\Python27\python.exe"
npm ERR! gyp verb check python version C:\Python27\python.exe -c "import sys; print "2.7.0 npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];" returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.2
npm ERR! gyp verb command install [ '16.13.2' ]
npm ERR! gyp verb install input version string "16.13.2"
npm ERR! gyp verb install installing version: 16.13.2
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.2
npm ERR! gyp verb build dir attempting to create "build" dir: C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-p
[2022-02-03T07_36_50_272Z-debug-0.log](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro/files/7992645/2022-02-03T07_36_50_272Z-debug-0.log)
ro-v1.6.0\node_modules\node-sass\build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\config.gypi
npm ERR! (node:41344) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use node --trace-deprecation ... to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\gyp\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-G',
npm ERR! gyp info spawn args 'msvs_version=2015',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\Users\user\.node-gyp\16.13.2\include\node\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\Users\user\.node-gyp\16.13.2',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\Users\user\.node-gyp\16.13.2\<(target_arch)\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\user.node-gyp\16.13.2
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb could not find "msbuild.exe" in PATH - finding location in registry
npm ERR! gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'build/binding.sln',
npm ERR! gyp info spawn args '/nologo',
npm ERR! gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.onExit (C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\lib\build.js:262:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\Users\user\AppData\Roaming\npm\node_modules\node\bin\node.exe" "C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\user\Downloads\now-ui-dashboard-pro-v1.6.0\now-ui-dashboard-pro-v1.6.0\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by miracle-HAC** [comment]
Hi, friends. I'm here to help you suffer.
I tried the method that the friends who commented above did, but it didn't work well.

You should install yarn and try  "yarn install " then
try "yarn start" 

good day!

**Comment by sajadevo** [comment]
**Hi everyone**

I've update the product and now everything working fine.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
