### ISSUE TITLE
Upgrading to reactstrap 5.0.0 and bootstrap 4.1.0

### ISSUE THREAD

**Issue by gbourne1** [creativetimofficial/ct-now-ui-dashboard-pro-react#8]
Upgrading to the non-alpha and beta packages breaks the input boxes with icons pre or appended. For example on the Registration page, the icons now show outside of the input boxes. Also on search icon on the homepage.

**Comment by einazare** [comment]
Hello again @gbourne1 ,

We are actively doing updates to our products. The problem is that this product depends on [another product of ours](https://demos.creative-tim.com/now-ui-dashboard-pro/examples/dashboard.html?_ga=2.31983737.618460419.1523863156-329288944.1519374311), and we need to make an update there, and after that we are going to make an update on this one. The update on that product has started, but at the same time we have other products that are being updated and i can not say how long it will take to make the update. I am expecting to make these updates by the end of this month - beginning of the next one.

Best,
Manu

**Comment by gbourne1** [comment]
Thank you - it is a good platform you built.
